let industries=[];
const defaultPendingUpdates=[{company:"Johnson Matthey",impact:"卡脖子判断",source:"官方资料 / 投资者材料",summary:"需要核验其燃料电池催化剂、CCM 与 MEA 业务在汽车客户中的验证进展。",status:"AI 候选"},{company:"FORVIA",impact:"财报/订单动态",source:"公司公告 / 财报",summary:"跟踪氢储能系统新订单、产能利用率和商用车客户。",status:"每周追踪"}];
const fallbackSources=[{id:"doe-fuel-cell-parts",title:"U.S. DOE fuel cell parts overview",type:"government",url:"https://www.energy.gov/eere/fuelcells/parts-fuel-cell",note:"支撑 PEM 燃料电池关键部件、MEA、双极板等基础结构。"},{id:"doe-hydrogen-storage",title:"U.S. DOE physical hydrogen storage",type:"government",url:"https://www.energy.gov/eere/fuelcells/physical-hydrogen-storage",note:"支撑 350bar/700bar 车载压缩氢储存路线。"},{id:"jm-fuel-cell-tech",title:"Johnson Matthey fuel cells technology",type:"company_official",url:"https://matthey.com/products-and-services/fuel-cells/fuel-cells-technology",note:"支撑 Johnson Matthey 在燃料电池催化剂、CCM、MEA 相关环节的业务描述。"},{id:"umicore-fuel-cell-catalysts",title:"Umicore fuel cell catalysts",type:"company_official",url:"https://www.umicore.com/en/markets-products/automotive-mobility/fuel-cell-catalysts/",note:"支撑 Umicore 燃料电池催化剂业务。"},{id:"sgl-gdl",title:"SGL Carbon SIGRACET fuel cell components",type:"company_official",url:"https://www.sglcarbon.com/en/markets-solutions/material/sigracet-fuel-cell-components/",note:"支撑 SGL Carbon GDL 与燃料电池组件业务。"},{id:"forvia-hydrogen-storage",title:"FORVIA hydrogen storage systems",type:"company_official",url:"https://www.forvia.com/en/pioneering-technologies/electrification-and-energy-management/hydrogen-storage-systems",note:"支撑 FORVIA 车载储氢系统业务。"},{id:"hexagon-purus",title:"Hexagon Purus hydrogen storage systems",type:"company_official",url:"https://hexagongroup.com/hexagon-purus",note:"支撑 Hexagon Purus 高压储氢瓶与系统业务。"},{id:"garrett-fuel-cell",title:"Garrett fuel cell technology",type:"company_official",url:"https://www.garrettmotion.com/electric-hybrid/fuel-cell-technology/",note:"支撑 Garrett 燃料电池空压机/空气管理相关业务。"}];
const fallbackCompanySources={jm:["jm-fuel-cell-tech","doe-fuel-cell-parts"],umicore:["umicore-fuel-cell-catalysts","doe-fuel-cell-parts"],forvia:["forvia-hydrogen-storage","doe-hydrogen-storage"],garrett:["garrett-fuel-cell"],toray:["doe-fuel-cell-parts"],sgl:["sgl-gdl","doe-fuel-cell-parts"],hexagon:["hexagon-purus","doe-hydrogen-storage"],toyota:["doe-fuel-cell-parts"],ballard:["doe-fuel-cell-parts"]};
const state={industry:null,pendingUpdates:loadPendingUpdates()};
const industrySelect=document.querySelector("#industry-select"),industryTitle=document.querySelector("#industry-title"),industryDescription=document.querySelector("#industry-description"),map=document.querySelector("#supply-chain-map"),pendingUpdates=document.querySelector("#pending-updates"),dialog=document.querySelector("#company-dialog"),detail=document.querySelector("#company-detail"),form=document.querySelector("#submission-form"),reviewFilter=document.querySelector("#review-filter");
async function boot(){try{industries=await loadIndustries();state.industry=industries[0];initIndustrySelect();bindInteractions();render()}catch(e){renderLoadError(e)}}
async function loadIndustries(){const r=await fetch("data/industries.json",{cache:"no-store"});if(!r.ok)throw new Error(`行业数据加载失败：${r.status}`);const d=await r.json();if(!Array.isArray(d)||!d.length)throw new Error("行业数据为空或格式不正确。");return d}
function loadPendingUpdates(){const s=localStorage.getItem("pendingUpdates");if(!s)return defaultPendingUpdates;try{return[...defaultPendingUpdates,...JSON.parse(s)]}catch{return defaultPendingUpdates}}
function saveUserUpdate(u){const s=localStorage.getItem("pendingUpdates"),a=s?JSON.parse(s):[];a.unshift(u);localStorage.setItem("pendingUpdates",JSON.stringify(a))}
function initIndustrySelect(){industrySelect.innerHTML="";industries.forEach(i=>{const o=document.createElement("option");o.value=i.id;o.textContent=i.name;industrySelect.appendChild(o)})}
function bindInteractions(){industrySelect.addEventListener("change",()=>{state.industry=industries.find(i=>i.id===industrySelect.value);render()});document.querySelector("#close-dialog").addEventListener("click",()=>dialog.close());document.querySelector("#reset-view").addEventListener("click",()=>map.scrollTo({left:0,top:0,behavior:"smooth"}));form.addEventListener("submit",handleSubmission);reviewFilter.addEventListener("change",renderPendingUpdates);pendingUpdates.addEventListener("click",handleReviewAction)}
function render(){industryTitle.textContent=state.industry.name;industryDescription.textContent=state.industry.description;renderMap();renderPendingUpdates()}
function renderMap(){const c=document.createElement("div");c.className="map-canvas";const maxX=Math.max(...state.industry.nodes.map(n=>n.position.x))+250,maxY=Math.max(...state.industry.nodes.map(n=>n.position.y))+140;c.style.width=`${maxX}px`;c.style.height=`${Math.max(maxY,680)}px`;const svg=document.createElementNS("http://www.w3.org/2000/svg","svg");svg.classList.add("edges");svg.setAttribute("width",maxX);svg.setAttribute("height",Math.max(maxY,680));state.industry.relationships.forEach(({from,to})=>{const s=state.industry.nodes.find(n=>n.id===from),e=state.industry.nodes.find(n=>n.id===to);if(!s||!e)return;const p=document.createElementNS("http://www.w3.org/2000/svg","path"),x1=s.position.x+190,y1=s.position.y+41,x2=e.position.x,y2=e.position.y+41,m=(x1+x2)/2;p.setAttribute("d",`M ${x1} ${y1} C ${m} ${y1}, ${m} ${y2}, ${x2} ${y2}`);p.setAttribute("fill","none");p.setAttribute("stroke","#b9aa96");p.setAttribute("stroke-width","2");svg.appendChild(p)});c.appendChild(svg);state.industry.nodes.forEach(n=>{const el=document.createElement("button");el.type="button";el.className=`node ${n.type}`;el.style.left=`${n.position.x}px`;el.style.top=`${n.position.y}px`;el.innerHTML=`<div class="node-title">${n.title}</div><div class="node-meta">${n.summary}</div><div class="tags">${n.tags.map(t=>`<span class="tag">${t}</span>`).join("")}</div>`;if(findCompany(n.id))el.addEventListener("click",()=>openCompany(n.id));c.appendChild(el)});map.innerHTML="";map.appendChild(c)}
function findCompany(id){return state.industry.companies.find(c=>c.id===id)}
function openCompany(id){const c=findCompany(id);if(!c)return;const scores=Object.entries(c.scores).map(([k,v])=>`<div class="score-row"><span>${scoreLabel(k)}</span><div class="bar"><span style="width:${v}%"></span></div><strong>${v}</strong></div>`).join("");const signals=Object.entries(c.signals).map(([k,v])=>`<div class="signal"><strong>${signalLabel(k)}</strong><span>${v}</span></div>`).join("");detail.innerHTML=`<div class="detail-header"><h2>${c.name}</h2><div class="detail-subtitle">${c.ticker} · ${c.region} · ${c.businessRole}</div></div><div class="signal-grid">${signals}</div><h3>紫苏叶评分</h3>${scores}<h3>最近动态 / 待验证事项</h3><ul class="recent-list">${c.recentUpdates.map(i=>`<li>${i}</li>`).join("")}</ul><h3>证据来源</h3>${renderSources(sourceIdsForCompany(c))}`;dialog.showModal()}
function scoreLabel(k){return{ supplyChainImportance:"供应链重要性",scarcity:"稀缺性",pricingPower:"定价权",switchingCost:"切换成本",validationBarrier:"验证壁垒",marketUnderappreciation:"市场低估"}[k]||k}
function signalLabel(k){return{importantSupplier:"重要供应商",bottleneckPosition:"卡脖子位置",playerConcentration:"玩家集中度",recentCatalyst:"近期催化剂"}[k]||k}
function allSources(){return[...(state.industry.sources||[]),...fallbackSources]}
function sourceById(id){return allSources().find(s=>s.id===id)}
function sourceIdsForCompany(c){return c.sourceIds||fallbackCompanySources[c.id]||[]}
function sourceIdsForEvent(e){if(e.sourceIds)return e.sourceIds;if(e.companyId&&fallbackCompanySources[e.companyId])return fallbackCompanySources[e.companyId];return[]}
function renderSources(ids=[]){const ss=ids.map(sourceById).filter(Boolean);if(!ss.length)return`<p class="source-empty">暂无绑定来源。</p>`;return`<div class="source-list">${ss.map(s=>`<div class="source-item"><strong>${s.title}</strong><span>${s.type} · ${s.note}</span>${s.url?`<a href="${s.url}" target="_blank" rel="noreferrer">查看来源</a>`:""}</div>`).join("")}</div>`}
function renderPendingUpdates(){const v=filterReviewQueue(buildReviewQueue());if(!v.length){pendingUpdates.innerHTML=`<div class="empty-state">当前筛选条件下没有更新事件。</div>`;return}pendingUpdates.innerHTML=v.map(u=>`<article class="update-card ${u.reviewStatus}"><strong>${u.company}</strong><span>${reviewStatusLabel(u.reviewStatus)} · ${u.impact}</span><p>${u.summary}</p><span>来源：${u.source}</span>${renderSources(u.sourceIds)}<div class="review-actions"><button type="button" data-review-id="${u.id}" data-review-status="approved">通过</button><button type="button" data-review-id="${u.id}" data-review-status="needs_more_evidence">补证据</button><button type="button" data-review-id="${u.id}" data-review-status="rejected">拒绝</button></div></article>`).join("")}
function buildReviewQueue(){const ie=state.industry.updateEvents.map(e=>({id:e.id,company:e.companyId||e.nodeId||state.industry.name,impact:e.impactType,source:e.sourceUrl||e.sourceNote||"未提供来源",sourceIds:sourceIdsForEvent(e),summary:e.summary,reviewStatus:reviewStatusFor(e.id,e.status)}));const ue=state.pendingUpdates.map(u=>({id:u.id||stableUpdateId(u),company:u.company,impact:u.impact,source:u.source,sourceIds:u.sourceIds||[],summary:u.summary,reviewStatus:reviewStatusFor(u.id||stableUpdateId(u),u.status)}));return[...ie,...ue]}
function stableUpdateId(u){return`legacy-${encodeURIComponent(`${u.company}-${u.source}-${u.summary}`)}`}
function filterReviewQueue(q){const s=reviewFilter.value;return s==="all"?q:q.filter(u=>u.reviewStatus===s)}
function reviewStatusFor(id,f){const d=loadReviewDecisions();return d[id]||normalizeReviewStatus(f)}
function normalizeReviewStatus(s){return["approved","rejected","needs_more_evidence","pending"].includes(s)?s:"pending"}
function reviewStatusLabel(s){return{pending:"待审核",approved:"已通过",rejected:"已拒绝",needs_more_evidence:"需补证据"}[s]||s}
function loadReviewDecisions(){const s=localStorage.getItem("reviewDecisions");if(!s)return{};try{return JSON.parse(s)}catch{return{}}}
function saveReviewDecision(id,status){const d=loadReviewDecisions();d[id]=status;localStorage.setItem("reviewDecisions",JSON.stringify(d))}
function handleReviewAction(e){const b=e.target.closest("[data-review-id]");if(!b)return;saveReviewDecision(b.dataset.reviewId,b.dataset.reviewStatus);renderPendingUpdates()}
function handleSubmission(e){e.preventDefault();const u={id:`user-${Date.now()}`,company:document.querySelector("#submission-company").value.trim(),source:document.querySelector("#submission-source").value.trim(),summary:document.querySelector("#submission-summary").value.trim(),impact:document.querySelector("#submission-impact").value,status:"pending"};saveUserUpdate(u);state.pendingUpdates.unshift(u);renderPendingUpdates();form.reset()}
function renderLoadError(e){industryTitle.textContent="行业数据加载失败";industryDescription.textContent="请通过本地网页服务或线上链接打开页面，直接双击本地文件时部分浏览器会限制 JSON 数据读取。";map.innerHTML=`<div class="load-error">${e.message}</div>`}
boot();